#pragma config(Motor,  motor1,          LeftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          RightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor11,         armLeft,       tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor12,         armRight,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//---------------(move arm)---------------------------------------------------------------------

void hang()
{
	//drive forward
setMotorSpeed(motor11, 127);
setMotorSpeed(motor12, 127);
delay(2400);

//stop
setMotorSpeed(motor11, 0);
setMotorSpeed(motor12, 0);

//move arm up
setMotorSpeed(motor1, 127);
setMotorSpeed(motor6, 127);
delay(1350);

//stop arm
setMotorSpeed(motor1, 0);
setMotorSpeed(motor6, 0);
delay(100);

//bring arm down
setMotorSpeed(motor11, -127);
setMotorSpeed(motor12, -127);
delay(4000);

//stop arm
setMotorSpeed(motor11, 0);
setMotorSpeed(motor12, 0);
delay(10000);
}
void armup(float rotations, int speed)
{
	resetMotorEncoder(motor11);
	resetMotorEncoder(motor12);
	setMotorTarget(motor11, 360*rotations ,-speed);
	setMotorTarget(motor12, 360*rotations , -speed);
	waitUntilMotorStop(motor11);
	waitUntilMotorStop(motor12);
	setMotorSpeed(motor11,0);
	setMotorSpeed(motor12,0);

}

void armdown(float rotations, int speed)
{
	resetMotorEncoder(motor11);
	resetMotorEncoder(motor12);
	setMotorTarget(motor11, 360*rotations ,speed);
	setMotorTarget(motor12, 360*rotations , speed);
	waitUntilMotorStop(motor11);
	waitUntilMotorStop(motor12);
  setMotorSpeed(motor11,0);
	setMotorSpeed(motor12,0);
}
//----------------(turn left)-----------------------------------------------------------------------
void turnleft(int degrees, int speed)
{
	resetGyro(port7);
	repeatUntil(getGyroDegrees(port7) > degrees){
		setMotorSpeed(motor1,-speed);
		setMotorSpeed(motor6,speed);
	}
}
//--------------(turn right)--------------------------------------------------------------
void turnright(int degrees, int speed)
{
	resetGyro(port7);
	repeatUntil(getGyroDegrees(port7) < -degrees){
		setMotorSpeed(motor1,speed);
		setMotorSpeed(motor6,-speed);
	}
}
//--------------(turn left)-----------------------------------------------------------------------------
void moveforward(float rotations, int speed)
{
	//reset the encoder to 0
	resetMotorEncoder(motor1);
	resetMotorEncoder(motor6);
	//convert rotations to degrees
	setMotorTarget(motor1,360*rotations,speed);
	setMotorTarget(motor6,360*rotations,speed);
	//keep moving motors until encoder reaches the value
	waitUntilMotorStop(motor1);
	waitUntilMotorStop(motor6);
}

void moveDistanceForward(float millimeters){
	//Wheel is 3 Inches = 72.6mm Diameter
	//Circumference	=PI*Diameter
	//C = 239.389

	float millimetersToRotations = 239.389;
	float rotations = millimeters/millimetersToRotations;
	moveforward(rotations,127);
}

task main()
{
	moveDistanceForward(100);
	turnleft(90, 127);
 moveDistanceForward(100);
	turnleft(90, 127);
	//go forward
//moveforward(0.5, 127);

//turnleft(85, 127);
//moveforward(2, 127);
//turnright(88, 127);
//moveforward(0.4, 127);
armup(4.5, 127);
sleep(1000);
//----------------(reverse)-----------------------------------------------------------------------------------------------
armdown(4.5, 127);
//moveforward(-0.4, 127);
//turnright(-88, 127);
//moveforward(-2, 127);
//turnleft(-85, 127);
//moveforward(-0.5, 127);
//hang();
}
